//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Say32.DB.Core.Exceptions {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessageFormat {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessageFormat() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Say32.DB.Core.Exceptions.ExceptionMessageFormat", typeof(ExceptionMessageFormat).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cannot purge when background operations are still running.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BaseDatabaseInstance_Cannot_purge_when_background_operations {
            get {
                return ResourceManager.GetString("BaseDatabaseInstance_Cannot_purge_when_background_operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete failed for type {0}: delete suppressed by trigger.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BaseDatabaseInstance_Delete_Delete_failed_for_type {
            get {
                return ResourceManager.GetString("BaseDatabaseInstance_Delete_Delete_failed_for_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Interceptor can&apos;t be null과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BaseDatabaseInstance_RegisterInterceptor_Interceptor_not_null {
            get {
                return ResourceManager.GetString("BaseDatabaseInstance_RegisterInterceptor_Interceptor_not_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save suppressed by trigger.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BaseDatabaseInstance_Save_Save_suppressed_by_trigger {
            get {
                return ResourceManager.GetString("BaseDatabaseInstance_Save_Save_suppressed_by_trigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot truncate when background operations are still running.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BaseDatabaseInstance_Truncate_Cannot_truncate_when_background_operations {
            get {
                return ResourceManager.GetString("BaseDatabaseInstance_Truncate_Cannot_truncate_when_background_operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The operation {0} is not allowed. A SayDB engine is already active for this application. You must dispose the engine before activating a new one.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SayDBActivationException {
            get {
                return ResourceManager.GetString("SayDBActivationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A definition for database with name {0} was not found.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SayDBDatabaseNotFoundException {
            get {
                return ResourceManager.GetString("SayDBDatabaseNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A database of type {0} has already been created. Only one database may exist.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SayDBDuplicateDatabaseException {
            get {
                return ResourceManager.GetString("SayDBDuplicateDatabaseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An index with the name {0} for type {1} already exists in SayDB database {1}.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SayDBDuplicateIndexException {
            get {
                return ResourceManager.GetString("SayDBDuplicateIndexException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A duplicate definition for type {0} already exists in SayDB database {1}.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SayDBDuplicateTypeException {
            get {
                return ResourceManager.GetString("SayDBDuplicateTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An index with the name {0} was not found for type {1}.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SayDBIndexNotFoundException {
            get {
                return ResourceManager.GetString("SayDBIndexNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There was an issue accessing isolated storage: {0}. Check the inner exception for details.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SayDBIsolatedStorageException {
            get {
                return ResourceManager.GetString("SayDBIsolatedStorageException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An attempt to unregister the logger with id {0} failed. The logger was not found.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SayDBLoggerNotFoundException {
            get {
                return ResourceManager.GetString("SayDBLoggerNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No table defintions were provided for the database. At least one table definition is required.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SayDBNoTableDefinitionsException {
            get {
                return ResourceManager.GetString("SayDBNoTableDefinitionsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Operation failed. SayDB is not activated. Call ISayDBDatabase.Activate() to prepare the database for use.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SayDBNotReadyException {
            get {
                return ResourceManager.GetString("SayDBNotReadyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SayDB does not support serialization of NULL properties (property {0} on type {1}).과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SayDBNullException {
            get {
                return ResourceManager.GetString("SayDBNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Serialization/deserialization failed because the serializer {0} could not process the type {1} requested.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SayDBSerializerException {
            get {
                return ResourceManager.GetString("SayDBSerializerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A definition for type {0} was not found in SayDB database {1}.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SayDBTableNotFoundException {
            get {
                return ResourceManager.GetString("SayDBTableNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SayDB trigger exception occurred for trigger {0}: {1}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SayDBTriggerException {
            get {
                return ResourceManager.GetString("SayDBTriggerException", resourceCulture);
            }
        }
    }
}
